"""
Single-file GTO bot — generated by build_single_file.py.
Do not edit directly. Edit the gto/ package and rebuild.

This file is the concatenation of:
    gto/hand_notation.py
    gto/ranges.py
    gto/position.py
    gto/strategy.py

Submission entry point is `decide(game_state)` at the bottom.
"""

# ============================================================
# gto/hand_notation.py
# ============================================================

RANKS = "23456789TJQKA"
RANK_VAL = {r: i for i, r in enumerate(RANKS)}


def canonical(cards):
    """Return canonical 'AKo' / 'AKs' / 'AA' notation from two cards.

    `cards` is a list/tuple of two strings like ["As", "Kh"].
    Card format is rank + suit, e.g. "As", "Td", "2c".
    """
    if len(cards) != 2:
        raise ValueError(f"Need exactly 2 cards, got {len(cards)}: {cards}")

    c1, c2 = cards[0], cards[1]
    r1, s1 = c1[0].upper(), c1[1].lower()
    r2, s2 = c2[0].upper(), c2[1].lower()

    if r1 not in RANK_VAL or r2 not in RANK_VAL:
        raise ValueError(f"Bad rank in {cards}")

    # Pair
    if r1 == r2:
        return r1 + r2

    # Sort so the higher rank is first
    if RANK_VAL[r1] < RANK_VAL[r2]:
        r1, r2 = r2, r1
        s1, s2 = s2, s1

    suited = "s" if s1 == s2 else "o"
    return r1 + r2 + suited


def is_pair(hand):
    """True if hand notation represents a pocket pair (e.g. 'AA', '77')."""
    return len(hand) == 2 and hand[0] == hand[1]


def is_suited(hand):
    """True if hand is a suited non-pair (e.g. 'AKs')."""
    return len(hand) == 3 and hand[2] == "s"


def all_169_hands():
    """Yield all 169 unique starting hands in standard notation."""
    for i, hi in enumerate(reversed(RANKS)):
        for j, lo in enumerate(reversed(RANKS)):
            if i == j:
                yield hi + hi
            elif i < j:
                yield hi + lo + "s"
            else:
                yield lo + hi + "o"

# ============================================================
# gto/equity.py
# ============================================================

import random

# ---------------------------------------------------------------------------
# Backend selection
# ---------------------------------------------------------------------------
_BACKEND = None

try:
    import eval7  # type: ignore
    _BACKEND = "eval7"
except ImportError:
    try:
        from treys import Card as _TCard, Evaluator as _TEval, Deck as _TDeck  # type: ignore
        _BACKEND = "treys"
        _TREYS_EV = _TEval()
        _TREYS_FULL_DECK = _TDeck.GetFullDeck()
    except ImportError:
        _BACKEND = None


# Pre-computed approximate preflop equities vs random (for fallback only —
# values from standard poker references; only used when no evaluator is
# available, e.g. during validator dry runs).
_PREFLOP_EQUITY_APPROX = {
    "AA": 0.85, "KK": 0.82, "QQ": 0.80, "JJ": 0.77, "TT": 0.75,
    "99": 0.72, "88": 0.69, "77": 0.66, "66": 0.63, "55": 0.60,
    "44": 0.57, "33": 0.54, "22": 0.50,
    "AKs": 0.67, "AKo": 0.65, "AQs": 0.66, "AQo": 0.64,
    "AJs": 0.65, "AJo": 0.63, "ATs": 0.64, "ATo": 0.61,
    "KQs": 0.63, "KQo": 0.61, "KJs": 0.62, "KJo": 0.59,
    "QJs": 0.60, "JTs": 0.58, "T9s": 0.54, "98s": 0.51,
    "87s": 0.48, "76s": 0.46, "65s": 0.44, "54s": 0.42,
}


# ---------------------------------------------------------------------------
# Backend-specific helpers
# ---------------------------------------------------------------------------
def _eval7_equity(hole_strs, board_strs, n_opp, n_iters):
    """Monte Carlo equity using eval7."""
    hole = [eval7.Card(c) for c in hole_strs]
    board = [eval7.Card(c) for c in board_strs]
    known = set(hole) | set(board)
    deck = [c for c in eval7.Deck().cards if c not in known]

    needed_board = 5 - len(board)
    wins = ties = 0
    for _ in range(n_iters):
        random.shuffle(deck)
        idx = 0
        opp_hands = []
        for _ in range(n_opp):
            opp_hands.append(deck[idx:idx + 2])
            idx += 2
        runout = deck[idx:idx + needed_board]
        full_board = board + runout
        my_rank = eval7.evaluate(hole + full_board)
        win = True
        tie = False
        for opp in opp_hands:
            opp_rank = eval7.evaluate(opp + full_board)
            if opp_rank > my_rank:
                win = False
                break
            elif opp_rank == my_rank:
                tie = True
        if win and not tie:
            wins += 1
        elif win and tie:
            ties += 1
    return (wins + ties * 0.5) / n_iters


def _treys_equity(hole_strs, board_strs, n_opp, n_iters):
    """Monte Carlo equity using treys (lower rank == better)."""
    hole = [_TCard.new(_treys_card(c)) for c in hole_strs]
    board = [_TCard.new(_treys_card(c)) for c in board_strs]
    known = set(hole) | set(board)
    deck = [c for c in _TREYS_FULL_DECK if c not in known]

    needed_board = 5 - len(board)
    wins = ties = 0
    for _ in range(n_iters):
        random.shuffle(deck)
        idx = 0
        opp_hands = []
        for _ in range(n_opp):
            opp_hands.append(deck[idx:idx + 2])
            idx += 2
        runout = deck[idx:idx + needed_board]
        full_board = board + runout
        my_rank = _TREYS_EV.evaluate(full_board, hole)
        win = True
        tie = False
        for opp in opp_hands:
            opp_rank = _TREYS_EV.evaluate(full_board, opp)
            if opp_rank < my_rank:  # treys: smaller is better
                win = False
                break
            elif opp_rank == my_rank:
                tie = True
        if win and not tie:
            wins += 1
        elif win and tie:
            ties += 1
    return (wins + ties * 0.5) / n_iters


def _treys_card(c):
    """Normalize 'As' / 'as' / '7d' to the casing treys wants ('As', '7d')."""
    return c[0].upper() + c[1].lower()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def equity_vs_random(hole_cards, board, n_opponents=1, n_iters=1500):
    """Estimate equity of `hole_cards` vs `n_opponents` random hands.

    Args:
        hole_cards: list of 2 card strings, e.g. ["As", "Kh"].
        board: 0-5 card strings.
        n_opponents: how many random opponents to simulate.
        n_iters: Monte Carlo iterations.

    Returns: equity in [0.0, 1.0]. Falls back to 0.5 (or an approximate
    preflop table value) if no evaluator backend is available.
    """
    if _BACKEND == "eval7":
        return _eval7_equity(hole_cards, board, n_opponents, n_iters)
    if _BACKEND == "treys":
        return _treys_equity(hole_cards, board, n_opponents, n_iters)
    # No backend — return a coarse guess.
    if not board and len(hole_cards) == 2:
        from .hand_notation import canonical
        h = canonical(hole_cards)
        return _PREFLOP_EQUITY_APPROX.get(h, 0.45)
    return 0.5


def hand_strength_class(equity):
    """Bucket an equity number into a coarse strength class.

    Returns one of: 'monster', 'strong', 'medium', 'weak_made', 'draw',
    'air'. Useful for branching in the postflop logic without writing a
    bunch of magic numbers inline.
    """
    if equity >= 0.85:
        return "monster"
    if equity >= 0.65:
        return "strong"
    if equity >= 0.50:
        return "medium"
    if equity >= 0.35:
        return "weak_made"
    if equity >= 0.22:
        return "draw"
    return "air"


def backend_name():
    """Return the active evaluator backend (debugging)."""
    return _BACKEND or "none"

# ============================================================
# gto/board.py
# ============================================================

def analyze(board):
    """Return a dict describing `board` (a list of 0-5 card strings).

    Keys:
        ncards:        len(board)
        suits:         {"s": int, "h": int, "d": int, "c": int}
        flush_present: True if 5+ of one suit
        flush_draw:    True if 4 of one suit (turn) or 3 of one suit on flop
        backdoor_fd:   True if 2 of one suit on flop only
        monotone:      True if all 3+ board cards same suit
        rainbow:       True if no two cards share a suit
        paired:        True if board has any pair (including trips)
        trips:         True if board has trips
        quads:         True if board has quads
        connected:     "high" / "medium" / "low" — how close ranks are
        straight_draw: True if open-ender / gutshot possible on board
        high_card:     numeric rank value of the highest card (0=2, 12=A)
        wetness:       float in [0, 1] — overall texture coordination
    """
    out = {
        "ncards": len(board),
        "suits": {"s": 0, "h": 0, "d": 0, "c": 0},
        "flush_present": False,
        "flush_draw": False,
        "backdoor_fd": False,
        "monotone": False,
        "rainbow": False,
        "paired": False,
        "trips": False,
        "quads": False,
        "connected": "low",
        "straight_draw": False,
        "high_card": 0,
        "wetness": 0.0,
    }
    if not board:
        return out

    ranks = []
    for c in board:
        r, s = c[0].upper(), c[1].lower()
        out["suits"][s] = out["suits"].get(s, 0) + 1
        ranks.append(RANK_VAL[r])
    ranks.sort()
    out["high_card"] = ranks[-1]

    max_suit = max(out["suits"].values())
    if max_suit >= 5:
        out["flush_present"] = True
    elif max_suit == 4:
        out["flush_draw"] = True
    elif max_suit == 3 and len(board) == 3:
        out["monotone"] = True
        out["flush_draw"] = True
    elif max_suit == 3 and len(board) >= 4:
        out["flush_draw"] = True
    elif max_suit == 2 and len(board) == 3:
        out["backdoor_fd"] = True

    nonzero_suits = sum(1 for c in out["suits"].values() if c > 0)
    if nonzero_suits == len(board) and len(board) >= 3:
        out["rainbow"] = True

    # Pairs / trips / quads
    rank_counts = {}
    for r in ranks:
        rank_counts[r] = rank_counts.get(r, 0) + 1
    counts = sorted(rank_counts.values(), reverse=True)
    if counts and counts[0] == 4:
        out["quads"] = True
        out["paired"] = True
    elif counts and counts[0] == 3:
        out["trips"] = True
        out["paired"] = True
    elif counts and counts[0] == 2:
        out["paired"] = True

    # Connectedness: gap between min and max.
    span = ranks[-1] - ranks[0] if len(ranks) >= 2 else 0
    if span <= 4:
        out["connected"] = "high"
    elif span <= 8:
        out["connected"] = "medium"
    else:
        out["connected"] = "low"

    # Straight-draw potential: any 3 cards within a 5-rank window?
    if len(ranks) >= 3:
        sr = sorted(set(ranks))
        for i in range(len(sr) - 2):
            if sr[i + 2] - sr[i] <= 4:
                out["straight_draw"] = True
                break

    # Wetness score: combine the above signals.
    w = 0.0
    if out["monotone"]:
        w += 0.45
    elif out["flush_draw"]:
        w += 0.35
    elif out["backdoor_fd"]:
        w += 0.10
    if out["straight_draw"]:
        w += 0.25
    if out["connected"] == "high":
        w += 0.20
    elif out["connected"] == "medium":
        w += 0.05
    if out["paired"]:
        w -= 0.05  # paired boards usually play "dryer" for ranges
    out["wetness"] = max(0.0, min(1.0, w))

    return out

# ============================================================
# gto/ranges.py
# ============================================================

# Action sizings — these come from the chart selections, in big blinds.
OPEN_SIZE_BB = {
    "UTG": 2.1,
    "UTG1": 2.1,
    "LJ": 2.1,
    "HJ": 2.1,
    "CO": 2.2,
    "BTN": 2.5,
    "SB": 3.5,
}


def _r(freq=1.0):
    """Helper: raise `freq` of the time, fold the rest."""
    return {"raise": freq, "fold": 1.0 - freq}


def _rc(raise_freq, call_freq):
    """Helper for SB: raise/call/fold mix."""
    fold = max(0.0, 1.0 - raise_freq - call_freq)
    return {"raise": raise_freq, "call": call_freq, "fold": fold}


# ---------------------------------------------------------------------------
# UTG — opens 16.9%
# ---------------------------------------------------------------------------
UTG = {
    # Pairs
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(),
    "77": _r(0.95), "66": _r(0.70), "55": _r(0.55),
    "44": _r(0.40), "33": _r(0.35), "22": _r(0.30),
    # Suited aces
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(), "A9s": _r(),
    "A8s": _r(0.95), "A7s": _r(0.85), "A6s": _r(0.75),
    "A5s": _r(0.95), "A4s": _r(0.85), "A3s": _r(0.75), "A2s": _r(0.60),
    # Offsuit aces
    "AKo": _r(), "AQo": _r(), "AJo": _r(0.95), "ATo": _r(0.60),
    # Kings
    "KQs": _r(), "KJs": _r(), "KTs": _r(0.95),
    "K9s": _r(0.55), "K8s": _r(0.25), "K7s": _r(0.10),
    "KQo": _r(0.85), "KJo": _r(0.40),
    # Queens
    "QJs": _r(), "QTs": _r(0.90), "Q9s": _r(0.40),
    "QJo": _r(0.30),
    # Jacks
    "JTs": _r(), "J9s": _r(0.45), "J8s": _r(0.05),
    # Tens
    "T9s": _r(0.95), "T8s": _r(0.25),
    # Connectors / suited gappers
    "98s": _r(0.75), "87s": _r(0.55), "76s": _r(0.40),
    "65s": _r(0.35), "54s": _r(0.25),
}


# ---------------------------------------------------------------------------
# UTG1 — opens 19.6%
# ---------------------------------------------------------------------------
UTG1 = {
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(),
    "77": _r(), "66": _r(0.95), "55": _r(0.80),
    "44": _r(0.65), "33": _r(0.55), "22": _r(0.50),
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(),
    "A9s": _r(), "A8s": _r(), "A7s": _r(),
    "A6s": _r(0.90), "A5s": _r(), "A4s": _r(0.95),
    "A3s": _r(0.85), "A2s": _r(0.70),
    "AKo": _r(), "AQo": _r(), "AJo": _r(), "ATo": _r(0.70),
    "A9o": _r(0.10),
    "KQs": _r(), "KJs": _r(), "KTs": _r(),
    "K9s": _r(0.75), "K8s": _r(0.40), "K7s": _r(0.20),
    "KQo": _r(0.95), "KJo": _r(0.55), "KTo": _r(0.15),
    "QJs": _r(), "QTs": _r(), "Q9s": _r(0.60),
    "Q8s": _r(0.10),
    "QJo": _r(0.45), "QTo": _r(0.05),
    "JTs": _r(), "J9s": _r(0.65), "J8s": _r(0.10),
    "JTo": _r(0.05),
    "T9s": _r(), "T8s": _r(0.45),
    "98s": _r(0.90), "87s": _r(0.75), "76s": _r(0.55),
    "65s": _r(0.45), "54s": _r(0.35),
    "64s": _r(0.05), "53s": _r(0.05),
}


# ---------------------------------------------------------------------------
# LJ — opens 23.2%
# ---------------------------------------------------------------------------
LJ = {
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(), "77": _r(),
    "66": _r(), "55": _r(0.95), "44": _r(0.85),
    "33": _r(0.75), "22": _r(0.70),
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(),
    "A9s": _r(), "A8s": _r(), "A7s": _r(),
    "A6s": _r(0.95), "A5s": _r(), "A4s": _r(),
    "A3s": _r(0.95), "A2s": _r(0.85),
    "AKo": _r(), "AQo": _r(), "AJo": _r(), "ATo": _r(0.90),
    "A9o": _r(0.30), "A8o": _r(0.05),
    "KQs": _r(), "KJs": _r(), "KTs": _r(),
    "K9s": _r(0.90), "K8s": _r(0.55), "K7s": _r(0.35),
    "K6s": _r(0.15), "K5s": _r(0.05),
    "KQo": _r(), "KJo": _r(0.80), "KTo": _r(0.35),
    "QJs": _r(), "QTs": _r(), "Q9s": _r(0.80),
    "Q8s": _r(0.25), "Q7s": _r(0.05),
    "QJo": _r(0.65), "QTo": _r(0.15),
    "JTs": _r(), "J9s": _r(0.85), "J8s": _r(0.25),
    "JTo": _r(0.10),
    "T9s": _r(), "T8s": _r(0.65), "T7s": _r(0.05),
    "98s": _r(), "87s": _r(0.90), "76s": _r(0.70),
    "65s": _r(0.55), "54s": _r(0.45),
    "64s": _r(0.15), "53s": _r(0.15),
    "43s": _r(0.05),
}


# ---------------------------------------------------------------------------
# HJ — opens 28.5%
# ---------------------------------------------------------------------------
HJ = {
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(), "77": _r(),
    "66": _r(), "55": _r(), "44": _r(0.95),
    "33": _r(0.85), "22": _r(0.80),
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(),
    "A9s": _r(), "A8s": _r(), "A7s": _r(),
    "A6s": _r(), "A5s": _r(), "A4s": _r(),
    "A3s": _r(), "A2s": _r(0.95),
    "AKo": _r(), "AQo": _r(), "AJo": _r(), "ATo": _r(),
    "A9o": _r(0.65), "A8o": _r(0.30), "A7o": _r(0.05),
    "A5o": _r(0.10),
    "KQs": _r(), "KJs": _r(), "KTs": _r(), "K9s": _r(),
    "K8s": _r(0.85), "K7s": _r(0.60), "K6s": _r(0.35),
    "K5s": _r(0.20), "K4s": _r(0.10),
    "KQo": _r(), "KJo": _r(), "KTo": _r(0.65),
    "K9o": _r(0.10),
    "QJs": _r(), "QTs": _r(), "Q9s": _r(),
    "Q8s": _r(0.55), "Q7s": _r(0.20), "Q6s": _r(0.05),
    "QJo": _r(0.85), "QTo": _r(0.45), "Q9o": _r(0.05),
    "JTs": _r(), "J9s": _r(), "J8s": _r(0.65),
    "J7s": _r(0.15),
    "JTo": _r(0.55), "J9o": _r(0.05),
    "T9s": _r(), "T8s": _r(0.90), "T7s": _r(0.30),
    "T9o": _r(0.05),
    "98s": _r(), "97s": _r(0.35),
    "87s": _r(), "86s": _r(0.20),
    "76s": _r(), "75s": _r(0.20),
    "65s": _r(), "64s": _r(0.35),
    "54s": _r(0.85), "53s": _r(0.30),
    "43s": _r(0.30), "42s": _r(0.05),
}


# ---------------------------------------------------------------------------
# CO — opens 37.1%
# ---------------------------------------------------------------------------
CO = {
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(), "77": _r(),
    "66": _r(), "55": _r(), "44": _r(), "33": _r(),
    "22": _r(),
    # All suited aces always in
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(),
    "A9s": _r(), "A8s": _r(), "A7s": _r(),
    "A6s": _r(), "A5s": _r(), "A4s": _r(),
    "A3s": _r(), "A2s": _r(),
    # Offsuit aces — A2o+ all play here
    "AKo": _r(), "AQo": _r(), "AJo": _r(), "ATo": _r(),
    "A9o": _r(), "A8o": _r(0.85), "A7o": _r(0.65),
    "A6o": _r(0.40), "A5o": _r(0.60), "A4o": _r(0.45),
    "A3o": _r(0.30), "A2o": _r(0.20),
    # Suited kings — all play, low ones mixed
    "KQs": _r(), "KJs": _r(), "KTs": _r(), "K9s": _r(),
    "K8s": _r(), "K7s": _r(0.95), "K6s": _r(0.80),
    "K5s": _r(0.65), "K4s": _r(0.45), "K3s": _r(0.35),
    "K2s": _r(0.25),
    # Offsuit kings
    "KQo": _r(), "KJo": _r(), "KTo": _r(0.95),
    "K9o": _r(0.55), "K8o": _r(0.10),
    # Queens — all suited play
    "QJs": _r(), "QTs": _r(), "Q9s": _r(),
    "Q8s": _r(0.95), "Q7s": _r(0.65), "Q6s": _r(0.45),
    "Q5s": _r(0.40), "Q4s": _r(0.25), "Q3s": _r(0.10),
    "Q2s": _r(0.05),
    "QJo": _r(), "QTo": _r(0.85), "Q9o": _r(0.40),
    "Q8o": _r(0.05),
    # Jacks
    "JTs": _r(), "J9s": _r(), "J8s": _r(0.95),
    "J7s": _r(0.55), "J6s": _r(0.10),
    "JTo": _r(0.85), "J9o": _r(0.35), "J8o": _r(0.05),
    # Tens
    "T9s": _r(), "T8s": _r(), "T7s": _r(0.85),
    "T6s": _r(0.20),
    "T9o": _r(0.55), "T8o": _r(0.05),
    # 9s and below — connectors/gappers
    "98s": _r(), "97s": _r(0.85), "96s": _r(0.30),
    "98o": _r(0.05),
    "87s": _r(), "86s": _r(0.75), "85s": _r(0.20),
    "76s": _r(), "75s": _r(0.65), "74s": _r(0.05),
    "65s": _r(), "64s": _r(0.65), "63s": _r(0.05),
    "54s": _r(), "53s": _r(0.55), "52s": _r(0.05),
    "43s": _r(0.65), "42s": _r(0.05),
    "32s": _r(0.20),
}


# ---------------------------------------------------------------------------
# BTN — opens 37.1% with a wider mix and bigger sizing (2.5bb)
# ---------------------------------------------------------------------------
# NOTE: BTN's chart looks similar in raise % to CO but the actual hand set
# is wider — it folds even less from low suited combos. Re-tune if you have
# better data on this specific spot.
BTN = {
    "AA": _r(), "KK": _r(), "QQ": _r(), "JJ": _r(),
    "TT": _r(), "99": _r(), "88": _r(), "77": _r(),
    "66": _r(), "55": _r(), "44": _r(), "33": _r(), "22": _r(),
    # All suited aces
    "AKs": _r(), "AQs": _r(), "AJs": _r(), "ATs": _r(),
    "A9s": _r(), "A8s": _r(), "A7s": _r(),
    "A6s": _r(), "A5s": _r(), "A4s": _r(),
    "A3s": _r(), "A2s": _r(),
    # Offsuit aces
    "AKo": _r(), "AQo": _r(), "AJo": _r(), "ATo": _r(),
    "A9o": _r(), "A8o": _r(0.90), "A7o": _r(0.65),
    "A6o": _r(0.30), "A5o": _r(0.55), "A4o": _r(0.35),
    "A3o": _r(0.20), "A2o": _r(0.10),
    # All suited kings
    "KQs": _r(), "KJs": _r(), "KTs": _r(), "K9s": _r(),
    "K8s": _r(), "K7s": _r(), "K6s": _r(), "K5s": _r(0.90),
    "K4s": _r(0.65), "K3s": _r(0.45), "K2s": _r(0.35),
    "KQo": _r(), "KJo": _r(), "KTo": _r(),
    "K9o": _r(0.55), "K8o": _r(0.10),
    # Queens
    "QJs": _r(), "QTs": _r(), "Q9s": _r(), "Q8s": _r(),
    "Q7s": _r(0.70), "Q6s": _r(0.55), "Q5s": _r(0.50),
    "Q4s": _r(0.30), "Q3s": _r(0.15), "Q2s": _r(0.05),
    "QJo": _r(), "QTo": _r(0.90), "Q9o": _r(0.45),
    "Q8o": _r(0.05),
    # Jacks
    "JTs": _r(), "J9s": _r(), "J8s": _r(),
    "J7s": _r(0.55), "J6s": _r(0.20),
    "JTo": _r(0.90), "J9o": _r(0.40), "J8o": _r(0.05),
    # Tens
    "T9s": _r(), "T8s": _r(), "T7s": _r(0.85),
    "T6s": _r(0.25),
    "T9o": _r(0.50), "T8o": _r(0.05),
    # Connectors / suited gappers
    "98s": _r(), "97s": _r(0.85), "96s": _r(0.30),
    "98o": _r(0.10),
    "87s": _r(), "86s": _r(0.75), "85s": _r(0.20),
    "76s": _r(), "75s": _r(0.65), "74s": _r(0.05),
    "65s": _r(), "64s": _r(0.65), "63s": _r(0.05),
    "54s": _r(), "53s": _r(0.55), "52s": _r(0.05),
    "43s": _r(0.65), "42s": _r(0.05),
    "32s": _r(0.20),
}


# ---------------------------------------------------------------------------
# SB — folded to SB heads-up vs BB. Raise/Call/Fold mix.
# Headline numbers from chart: Raise 9%, Call 81.4%, Fold 9.6%.
# Strategy is heavily limp-based at this stack/format.
# ---------------------------------------------------------------------------
# Encoding: only hands that DON'T do "always call" — everything missing
# defaults to call (since SB limps ~81%, that's the default action). Hands
# listed here override with raise / fold frequencies.
SB_OVERRIDES = {
    # Premium raises
    "AA": _rc(1.0, 0.0), "KK": _rc(1.0, 0.0),
    "QQ": _rc(0.95, 0.05), "JJ": _rc(0.85, 0.15),
    "AKs": _rc(0.95, 0.05), "AKo": _rc(0.95, 0.05),
    "AQs": _rc(0.80, 0.20), "AQo": _rc(0.70, 0.30),
    "AJs": _rc(0.50, 0.50), "ATs": _rc(0.30, 0.70),
    "KQs": _rc(0.40, 0.60),
    # Some semi-bluff raises that are pure-fold-on-3bet?  Not in this chart,
    # left as call.
    # Pure folds — the very weakest hands
    "83o": _rc(0.0, 0.0), "73o": _rc(0.0, 0.0),
    "63o": _rc(0.0, 0.0), "53o": _rc(0.0, 0.0),
    "93o": _rc(0.0, 0.0), "92o": _rc(0.0, 0.0),
    "82o": _rc(0.0, 0.0), "72o": _rc(0.0, 0.0),
    "62o": _rc(0.0, 0.0), "52o": _rc(0.0, 0.0),
    "42o": _rc(0.0, 0.0), "43o": _rc(0.0, 0.0),
    "32o": _rc(0.0, 0.0), "33":  _rc(0.0, 1.0),  # 33 mostly calls
}


def sb_action(hand):
    """SB's policy when folded to it heads-up vs BB."""
    if hand in SB_OVERRIDES:
        return SB_OVERRIDES[hand]
    # Default: call (limp).
    return {"raise": 0.0, "call": 1.0, "fold": 0.0}


# ---------------------------------------------------------------------------
# Position registry — one entry per supported chart.
# ---------------------------------------------------------------------------
RANGES_BY_POSITION = {
    "UTG": UTG,
    "UTG1": UTG1,
    "LJ": LJ,
    "HJ": HJ,
    "CO": CO,
    "BTN": BTN,
}


def get_open_action(position, hand):
    """Look up the unopened-pot action distribution for `hand` at `position`.

    Returns: dict like {"raise": 0.85, "fold": 0.15} (frequencies sum to 1.0).
    For positions we don't have a chart for, returns 100% fold.
    """
    if position == "SB":
        return sb_action(hand)
    table = RANGES_BY_POSITION.get(position)
    if table is None:
        return {"raise": 0.0, "fold": 1.0}
    return table.get(hand, {"raise": 0.0, "fold": 1.0})


def range_size_pct(position):
    """Return the approximate raise percentage of `position`'s RFI range."""
    if position == "SB":
        # 9% raise + 81.4% call from chart
        return 9.0
    table = RANGES_BY_POSITION.get(position)
    if table is None:
        return 0.0
    total_weight = 0.0
    total_combos = 0.0
    for hand in all_169_hands():
        combos = 6 if len(hand) == 2 else (4 if hand[2] == "s" else 12)
        raise_freq = table.get(hand, {}).get("raise", 0.0)
        total_weight += combos * raise_freq
        total_combos += combos
    return 100.0 * total_weight / total_combos

# ============================================================
# gto/defense.py
# ============================================================

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _d(three_bet=0.0, call=0.0):
    """Build an action distribution. Whatever's left is fold."""
    fold = max(0.0, 1.0 - three_bet - call)
    return {"3bet": three_bet, "call": call, "fold": fold}


# ---------------------------------------------------------------------------
# vs EARLY position opener (UTG / UTG1 in 8-max, UTG in 6-max)
# Opener's range is tight, so we play tight back.
# ---------------------------------------------------------------------------
VS_EARLY_IP = {
    # Always 3bet for value
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.85, 0.15), "JJ": _d(0.30, 0.70),
    "AKs": _d(0.80, 0.20), "AKo": _d(0.80, 0.20),
    "AQs": _d(0.30, 0.70),
    # Calls — set-mining and broadways
    "TT": _d(0.0, 1.0), "99": _d(0.0, 1.0), "88": _d(0.0, 1.0),
    "77": _d(0.0, 1.0), "66": _d(0.0, 0.8), "55": _d(0.0, 0.5),
    "AQo": _d(0.0, 0.85), "AJs": _d(0.0, 1.0), "ATs": _d(0.0, 0.8),
    "KQs": _d(0.0, 1.0), "KJs": _d(0.0, 0.7),
    "QJs": _d(0.0, 0.6), "JTs": _d(0.0, 0.7),
    "T9s": _d(0.0, 0.5), "98s": _d(0.0, 0.3),
    # Bluffs
    "A5s": _d(0.25, 0.0), "A4s": _d(0.20, 0.0),
}

VS_EARLY_OOP = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.95, 0.05), "JJ": _d(0.45, 0.55),
    "AKs": _d(0.85, 0.15), "AKo": _d(0.85, 0.15),
    "AQs": _d(0.50, 0.50),
    # OOP we call less, fold more
    "TT": _d(0.0, 0.90), "99": _d(0.0, 0.7), "88": _d(0.0, 0.5),
    "77": _d(0.0, 0.4), "66": _d(0.0, 0.3),
    "AQo": _d(0.0, 0.4), "AJs": _d(0.0, 0.6),
    "KQs": _d(0.0, 0.6), "KJs": _d(0.0, 0.3),
    "QJs": _d(0.0, 0.3), "JTs": _d(0.0, 0.3),
    # Bluffs (carefully — OOP bluffs are expensive)
    "A5s": _d(0.20, 0.0),
}

VS_EARLY_BB = {
    # Closing action — call wider, 3-bet less (more passive)
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.80, 0.20), "JJ": _d(0.30, 0.70),
    "TT": _d(0.0, 1.0), "99": _d(0.0, 1.0), "88": _d(0.0, 1.0),
    "77": _d(0.0, 1.0), "66": _d(0.0, 1.0), "55": _d(0.0, 0.9),
    "44": _d(0.0, 0.7), "33": _d(0.0, 0.5), "22": _d(0.0, 0.4),
    "AKs": _d(0.70, 0.30), "AKo": _d(0.60, 0.40),
    "AQs": _d(0.30, 0.70), "AQo": _d(0.0, 0.9),
    "AJs": _d(0.0, 1.0), "AJo": _d(0.0, 0.7),
    "ATs": _d(0.0, 1.0), "A9s": _d(0.0, 0.8), "A8s": _d(0.0, 0.5),
    "A5s": _d(0.20, 0.4), "A4s": _d(0.0, 0.4),
    "KQs": _d(0.0, 1.0), "KQo": _d(0.0, 0.6),
    "KJs": _d(0.0, 0.9), "KTs": _d(0.0, 0.7),
    "QJs": _d(0.0, 0.9), "QTs": _d(0.0, 0.5),
    "JTs": _d(0.0, 0.9), "T9s": _d(0.0, 0.7),
    "98s": _d(0.0, 0.5), "87s": _d(0.0, 0.4), "76s": _d(0.0, 0.3),
}


# ---------------------------------------------------------------------------
# vs MIDDLE position opener (LJ, HJ)
# Opener's range a touch wider — we widen too.
# ---------------------------------------------------------------------------
VS_MIDDLE_IP = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.90, 0.10), "JJ": _d(0.50, 0.50),
    "TT": _d(0.20, 0.75),
    "AKs": _d(0.80, 0.20), "AKo": _d(0.80, 0.20),
    "AQs": _d(0.50, 0.50), "AQo": _d(0.20, 0.65),
    "AJs": _d(0.10, 0.85),
    "99": _d(0.0, 1.0), "88": _d(0.0, 1.0), "77": _d(0.0, 1.0),
    "66": _d(0.0, 0.9), "55": _d(0.0, 0.7), "44": _d(0.0, 0.5),
    "ATs": _d(0.0, 1.0), "A9s": _d(0.0, 0.5),
    "KQs": _d(0.0, 1.0), "KJs": _d(0.0, 0.9), "KTs": _d(0.0, 0.6),
    "KQo": _d(0.0, 0.6),
    "QJs": _d(0.0, 0.9), "QTs": _d(0.0, 0.6),
    "JTs": _d(0.0, 0.9), "T9s": _d(0.0, 0.7),
    "98s": _d(0.0, 0.5), "87s": _d(0.0, 0.4),
    # Bluffs
    "A5s": _d(0.40, 0.0), "A4s": _d(0.30, 0.0), "A3s": _d(0.20, 0.0),
    "K9s": _d(0.20, 0.0),
}

VS_MIDDLE_OOP = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.95, 0.05), "JJ": _d(0.65, 0.35),
    "TT": _d(0.30, 0.50),
    "AKs": _d(0.85, 0.15), "AKo": _d(0.85, 0.15),
    "AQs": _d(0.60, 0.30), "AQo": _d(0.30, 0.40),
    "99": _d(0.0, 0.7), "88": _d(0.0, 0.5),
    "77": _d(0.0, 0.4), "66": _d(0.0, 0.3),
    "AJs": _d(0.0, 0.5),
    "KQs": _d(0.0, 0.6), "KJs": _d(0.0, 0.3),
    "QJs": _d(0.0, 0.3), "JTs": _d(0.0, 0.3),
    "A5s": _d(0.30, 0.0), "A4s": _d(0.20, 0.0),
}

VS_MIDDLE_BB = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.85, 0.15), "JJ": _d(0.45, 0.55),
    "TT": _d(0.0, 1.0), "99": _d(0.0, 1.0), "88": _d(0.0, 1.0),
    "77": _d(0.0, 1.0), "66": _d(0.0, 1.0), "55": _d(0.0, 1.0),
    "44": _d(0.0, 0.9), "33": _d(0.0, 0.7), "22": _d(0.0, 0.6),
    "AKs": _d(0.75, 0.25), "AKo": _d(0.65, 0.35),
    "AQs": _d(0.40, 0.60), "AQo": _d(0.10, 0.85),
    "AJs": _d(0.0, 1.0), "AJo": _d(0.0, 0.85),
    "ATs": _d(0.0, 1.0), "ATo": _d(0.0, 0.7),
    "A9s": _d(0.0, 0.95), "A8s": _d(0.0, 0.7),
    "A7s": _d(0.0, 0.6), "A6s": _d(0.0, 0.5),
    "A5s": _d(0.30, 0.5), "A4s": _d(0.20, 0.5), "A3s": _d(0.0, 0.4),
    "KQs": _d(0.0, 1.0), "KQo": _d(0.0, 0.8),
    "KJs": _d(0.0, 0.95), "KJo": _d(0.0, 0.5),
    "KTs": _d(0.0, 0.9), "K9s": _d(0.0, 0.6),
    "QJs": _d(0.0, 1.0), "QTs": _d(0.0, 0.8), "Q9s": _d(0.0, 0.4),
    "JTs": _d(0.0, 1.0), "T9s": _d(0.0, 0.9),
    "98s": _d(0.0, 0.7), "87s": _d(0.0, 0.6),
    "76s": _d(0.0, 0.5), "65s": _d(0.0, 0.4), "54s": _d(0.0, 0.3),
}


# ---------------------------------------------------------------------------
# vs LATE position opener (CO, BTN)
# Opener has a wide range — we widen aggressively and add bluffs.
# ---------------------------------------------------------------------------
VS_LATE_IP = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.95, 0.05), "JJ": _d(0.75, 0.25),
    "TT": _d(0.50, 0.40),
    "AKs": _d(0.80, 0.20), "AKo": _d(0.80, 0.20),
    "AQs": _d(0.65, 0.30), "AQo": _d(0.45, 0.45),
    "AJs": _d(0.35, 0.60), "AJo": _d(0.20, 0.55),
    "99": _d(0.20, 0.70), "88": _d(0.10, 0.80),
    "77": _d(0.0, 0.85), "66": _d(0.0, 0.7),
    "ATs": _d(0.10, 0.85), "ATo": _d(0.0, 0.45),
    "KQs": _d(0.30, 0.60), "KQo": _d(0.20, 0.50),
    "KJs": _d(0.20, 0.60), "KTs": _d(0.0, 0.75),
    "QJs": _d(0.15, 0.65), "QTs": _d(0.0, 0.65),
    "JTs": _d(0.10, 0.75), "T9s": _d(0.0, 0.65),
    "98s": _d(0.0, 0.5), "87s": _d(0.0, 0.4), "76s": _d(0.0, 0.3),
    # Bluffs — suited aces & connectors as light 3-bets
    "A5s": _d(0.70, 0.0), "A4s": _d(0.55, 0.0),
    "A3s": _d(0.45, 0.0), "A2s": _d(0.30, 0.0),
    "K9s": _d(0.30, 0.0), "Q9s": _d(0.20, 0.0),
    "J9s": _d(0.15, 0.0), "T8s": _d(0.10, 0.0),
}

VS_LATE_OOP = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(1.0, 0.0), "JJ": _d(0.85, 0.15),
    "TT": _d(0.55, 0.30),
    "AKs": _d(0.90, 0.10), "AKo": _d(0.85, 0.15),
    "AQs": _d(0.75, 0.20), "AQo": _d(0.55, 0.30),
    "AJs": _d(0.40, 0.30), "AJo": _d(0.25, 0.30),
    "99": _d(0.25, 0.45), "88": _d(0.15, 0.45),
    "77": _d(0.0, 0.55), "66": _d(0.0, 0.4),
    "ATs": _d(0.0, 0.55), "ATo": _d(0.0, 0.20),
    "KQs": _d(0.30, 0.45), "KQo": _d(0.20, 0.30),
    "KJs": _d(0.20, 0.40), "QJs": _d(0.15, 0.40),
    "JTs": _d(0.10, 0.45), "T9s": _d(0.0, 0.35),
    # Bluffs (a bit fewer OOP)
    "A5s": _d(0.55, 0.0), "A4s": _d(0.45, 0.0),
    "A3s": _d(0.30, 0.0), "K9s": _d(0.20, 0.0),
}

VS_LATE_BB = {
    "AA": _d(1.0, 0.0), "KK": _d(1.0, 0.0),
    "QQ": _d(0.95, 0.05), "JJ": _d(0.65, 0.35),
    "TT": _d(0.30, 0.65),
    "AKs": _d(0.80, 0.20), "AKo": _d(0.75, 0.25),
    "AQs": _d(0.50, 0.50), "AQo": _d(0.30, 0.65),
    "AJs": _d(0.20, 0.80), "AJo": _d(0.0, 1.0),
    "ATs": _d(0.0, 1.0), "ATo": _d(0.0, 0.95),
    "99": _d(0.0, 1.0), "88": _d(0.0, 1.0), "77": _d(0.0, 1.0),
    "66": _d(0.0, 1.0), "55": _d(0.0, 1.0), "44": _d(0.0, 1.0),
    "33": _d(0.0, 0.95), "22": _d(0.0, 0.9),
    "A9s": _d(0.0, 1.0), "A8s": _d(0.0, 1.0), "A7s": _d(0.0, 1.0),
    "A6s": _d(0.0, 1.0), "A5s": _d(0.50, 0.5), "A4s": _d(0.40, 0.6),
    "A3s": _d(0.25, 0.7), "A2s": _d(0.0, 0.85),
    "A9o": _d(0.0, 0.9), "A8o": _d(0.0, 0.7), "A7o": _d(0.0, 0.5),
    "KQs": _d(0.20, 0.80), "KQo": _d(0.0, 1.0),
    "KJs": _d(0.0, 1.0), "KJo": _d(0.0, 0.9),
    "KTs": _d(0.0, 1.0), "KTo": _d(0.0, 0.7),
    "K9s": _d(0.30, 0.7), "K8s": _d(0.0, 0.8), "K7s": _d(0.0, 0.6),
    "K9o": _d(0.0, 0.5),
    "QJs": _d(0.0, 1.0), "QJo": _d(0.0, 0.85),
    "QTs": _d(0.0, 1.0), "QTo": _d(0.0, 0.6),
    "Q9s": _d(0.20, 0.8), "Q8s": _d(0.0, 0.7),
    "JTs": _d(0.0, 1.0), "JTo": _d(0.0, 0.7),
    "J9s": _d(0.10, 0.85), "J8s": _d(0.0, 0.5),
    "T9s": _d(0.0, 1.0), "T8s": _d(0.0, 0.7),
    "98s": _d(0.0, 1.0), "87s": _d(0.0, 0.95),
    "76s": _d(0.0, 0.85), "65s": _d(0.0, 0.7),
    "54s": _d(0.0, 0.6), "43s": _d(0.0, 0.3),
    "97s": _d(0.0, 0.5), "86s": _d(0.0, 0.4),
}


# ---------------------------------------------------------------------------
# 4-bet defense: facing a 3-bet after we opened.
# Very tight at 100bb: jam AA-QQ and AKs, fold the rest by default.
# (KK gets a tiny call-or-4bet mix to balance.)
# ---------------------------------------------------------------------------
VS_3BET_DEFENSE = {
    "AA": _d(1.0, 0.0), "KK": _d(0.95, 0.05),
    "QQ": _d(0.50, 0.50), "JJ": _d(0.0, 0.85),
    "TT": _d(0.0, 0.65), "99": _d(0.0, 0.40),
    "88": _d(0.0, 0.25),
    "AKs": _d(0.85, 0.15), "AKo": _d(0.50, 0.50),
    "AQs": _d(0.0, 0.85), "AQo": _d(0.0, 0.30),
    "AJs": _d(0.0, 0.60), "ATs": _d(0.0, 0.35),
    "KQs": _d(0.0, 0.55), "KJs": _d(0.0, 0.20),
    "QJs": _d(0.0, 0.20), "JTs": _d(0.0, 0.20),
    # Small bluff 4-bets with blockers
    "A5s": _d(0.15, 0.0), "A4s": _d(0.10, 0.0),
}


# ---------------------------------------------------------------------------
# Routing helpers
# ---------------------------------------------------------------------------
OPENER_TIER = {
    "UTG": "EARLY",  "UTG1": "EARLY",
    "LJ":  "MIDDLE", "HJ":   "MIDDLE",
    "CO":  "LATE",   "BTN":  "LATE",
    "SB":  "LATE",
}


def defender_role(opener_pos, our_pos):
    """Decide which of our defense tables to use given seats.

    - If we're BB and closing the action  -> "BB"
    - If we'll be in position post-flop   -> "IP"
    - Otherwise                            -> "OOP"
    """
    if our_pos == "BB":
        return "BB"

    # Pre-flop seat order from earliest to latest (for action sequence):
    order = ["UTG", "UTG1", "LJ", "HJ", "CO", "BTN", "SB", "BB"]
    try:
        opp_idx = order.index(opener_pos)
        my_idx = order.index(our_pos)
    except ValueError:
        return "OOP"

    # Post-flop, BTN is most IP, SB/BB OOP. If our seat acts AFTER the
    # opener post-flop (closer to BTN cyclically), we're IP.
    # Simple rule: if our_pos is later in the action order pre-flop and
    # we're not in the blinds, we'll be IP post-flop too.
    if our_pos in ("SB", "BB"):
        return "BB" if our_pos == "BB" else "OOP"
    return "IP" if my_idx > opp_idx else "OOP"


# Lookup table
_DEFENSE_TABLES = {
    ("EARLY", "IP"):    VS_EARLY_IP,
    ("EARLY", "OOP"):   VS_EARLY_OOP,
    ("EARLY", "BB"):    VS_EARLY_BB,
    ("MIDDLE", "IP"):   VS_MIDDLE_IP,
    ("MIDDLE", "OOP"):  VS_MIDDLE_OOP,
    ("MIDDLE", "BB"):   VS_MIDDLE_BB,
    ("LATE", "IP"):     VS_LATE_IP,
    ("LATE", "OOP"):    VS_LATE_OOP,
    ("LATE", "BB"):     VS_LATE_BB,
}


def defense_action(opener_pos, our_pos, hand):
    """Return action distribution for our `hand` facing a raise from
    `opener_pos`.

    The returned dict has keys "3bet", "call", "fold" (summing to 1.0). It
    is up to the strategy layer to convert "3bet" into a bet sizing.
    """
    tier = OPENER_TIER.get(opener_pos, "MIDDLE")
    role = defender_role(opener_pos, our_pos)
    table = _DEFENSE_TABLES.get((tier, role), VS_MIDDLE_OOP)
    return table.get(hand, _d(0.0, 0.0))


def four_bet_defense(hand):
    """Return action distribution for `hand` facing a 3-bet after we opened.

    Keys: "3bet" (which here means 4-bet/jam), "call", "fold".
    """
    return VS_3BET_DEFENSE.get(hand, _d(0.0, 0.0))

# ============================================================
# gto/pushfold.py
# ============================================================

# Hands listed are inclusive — we jam THIS hand and everything stronger
# in the same family. Each set is checked directly though, so just list
# what we want.

# ---------------------------------------------------------------------------
# OPEN-JAM (we're first in)
# ---------------------------------------------------------------------------
# At ~20bb we jam tight; we get progressively looser as stack shrinks.

JAM_20BB = {
    "UTG": {
        "AA", "KK", "QQ", "JJ", "TT", "99", "88",
        "AKs", "AKo", "AQs", "AQo", "AJs",
    },
    "HJ": {
        "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77", "66",
        "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs", "KQs",
    },
    "CO": {
        "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77", "66", "55",
        "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs", "ATo",
        "A9s", "A8s", "A7s", "A5s", "KQs", "KQo", "KJs", "QJs",
    },
    "BTN": {
        "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77", "66", "55", "44", "33", "22",
        "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs", "ATo", "A9s", "A9o",
        "A8s", "A8o", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
        "KQs", "KQo", "KJs", "KJo", "KTs", "KTo", "K9s", "K8s",
        "QJs", "QJo", "QTs", "Q9s", "JTs", "J9s", "T9s", "98s", "87s",
    },
    "SB": {
        "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77", "66", "55", "44", "33", "22",
        "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs", "ATo", "A9s", "A9o",
        "A8s", "A8o", "A7s", "A7o", "A6s", "A5s", "A5o", "A4s", "A3s", "A2s",
        "KQs", "KQo", "KJs", "KJo", "KTs", "KTo", "K9s", "K9o", "K8s", "K7s",
        "QJs", "QJo", "QTs", "QTo", "Q9s", "Q8s",
        "JTs", "JTo", "J9s", "T9s", "T8s", "98s", "87s", "76s", "65s",
    },
}

JAM_12BB = {
    # At 12bb we widen substantially.
    "UTG":  JAM_20BB["UTG"] | {"77", "66", "AJo", "KQs"},
    "HJ":   JAM_20BB["HJ"]  | {"55", "44", "ATo", "KQo", "KJs", "QJs"},
    "CO":   JAM_20BB["CO"]  | {"44", "33", "22", "KJo", "KTs", "K9s", "QJo", "QTs", "JTs", "T9s"},
    "BTN":  JAM_20BB["BTN"] | {"KTo", "K9o", "K8s", "K7s", "Q8s", "Q7s",
                                "J8s", "T8s", "97s", "86s", "76s", "65s", "54s"},
    "SB":   JAM_20BB["SB"]  | {"K8o", "K7o", "Q8o", "Q7s", "J8s", "T7s", "97s", "86s", "75s", "54s"},
}

JAM_8BB = {
    # At ≤8bb we jam very wide.
    "UTG":  JAM_12BB["UTG"] | {"55", "44", "ATo", "KJs", "QJs"},
    "HJ":   JAM_12BB["HJ"]  | {"33", "22", "A6o", "K9s", "JTs"},
    "CO":   JAM_12BB["CO"]  | {"K7s", "Q8s", "J8s", "T8s", "97s", "76s", "65s"},
    "BTN":  JAM_12BB["BTN"] | {"K6s", "K5s", "Q6s", "J7s", "T7s", "96s", "85s", "75s", "64s", "53s", "43s"},
    "SB":   JAM_12BB["SB"]  | {"K6s", "K5s", "K4s", "Q6s", "Q5s", "Q4s", "J7s", "J6s", "T6s", "96s",
                                "85s", "74s", "63s", "52s", "32s", "43s"},
}


def open_jam_hands(effective_bb, position):
    """Return the set of hands we should open-jam at `effective_bb` from `position`."""
    pos = position if position in JAM_20BB else _map_position(position)
    if effective_bb <= 8:
        return JAM_8BB.get(pos, set())
    if effective_bb <= 12:
        return JAM_12BB.get(pos, set())
    if effective_bb <= 20:
        return JAM_20BB.get(pos, set())
    return set()


# ---------------------------------------------------------------------------
# CALL-A-JAM
# ---------------------------------------------------------------------------
# Calling all-in is fundamentally about pot odds & blockers. These ranges
# are calibrated for facing a typical short-stack jam — they should
# probably tighten vs a known nit and loosen vs a known maniac.

CALL_JAM_VS_LATE = {
    # vs a CO/BTN jam — they're wider, so we call wider.
    "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77",
    "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs",
    "KQs", "KQo", "KJs", "QJs",
}

CALL_JAM_VS_MIDDLE = {
    # vs HJ/LJ jam — slightly tighter.
    "AA", "KK", "QQ", "JJ", "TT", "99", "88",
    "AKs", "AKo", "AQs", "AQo", "AJs", "ATs",
    "KQs",
}

CALL_JAM_VS_EARLY = {
    # vs UTG/UTG1 jam — very tight.
    "AA", "KK", "QQ", "JJ", "TT",
    "AKs", "AKo", "AQs",
}

CALL_JAM_VS_BLIND = {
    # vs SB jam (or limp+jam) — quite wide.
    "AA", "KK", "QQ", "JJ", "TT", "99", "88", "77", "66", "55",
    "AKs", "AKo", "AQs", "AQo", "AJs", "AJo", "ATs", "ATo", "A9s",
    "KQs", "KQo", "KJs", "KJo", "KTs", "QJs", "QTs", "JTs",
}


def call_jam_range(jammer_position):
    """Set of hands that call an all-in from `jammer_position`."""
    if jammer_position in ("UTG", "UTG1"):
        return CALL_JAM_VS_EARLY
    if jammer_position in ("LJ", "HJ"):
        return CALL_JAM_VS_MIDDLE
    if jammer_position in ("CO", "BTN"):
        return CALL_JAM_VS_LATE
    if jammer_position == "SB":
        return CALL_JAM_VS_BLIND
    return CALL_JAM_VS_MIDDLE


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
def effective_stack_bb(state):
    """Compute the effective stack in big blinds.

    Uses our stack against the largest opponent stack (since that's the
    most we can lose/win in a single hand). Falls back to our stack alone
    if opponent data isn't available.
    """
    bb = state.get("big_blind") or 1
    my_stack = state.get("your_stack", 0)

    opp_stacks = []
    for p in state.get("players", []):
        if not isinstance(p, dict):
            continue
        if p.get("is_me") or p.get("is_self") or p.get("hero"):
            continue
        if p.get("folded") or p.get("status") == "folded":
            continue
        stack = p.get("stack") or p.get("chips") or 0
        if stack > 0:
            opp_stacks.append(stack)

    if opp_stacks:
        eff = min(my_stack, max(opp_stacks))
    else:
        eff = my_stack
    return eff / bb if bb else eff


def _map_position(pos):
    """Map 6-max-only positions to nearest jam-table key."""
    # We have UTG/HJ/CO/BTN/SB in the tables; 6-max position is one of these
    # already after the chart_position() mapping. Default to BTN if unknown.
    if pos in ("UTG", "UTG1"):
        return "UTG"
    if pos in ("LJ", "HJ", "MP"):
        return "HJ"
    return pos if pos in JAM_20BB else "BTN"

# ============================================================
# gto/position.py
# ============================================================

# Standard 8-max chart positions, in action order pre-flop.
EIGHTMAX_ORDER = ["UTG", "UTG1", "LJ", "HJ", "CO", "BTN", "SB", "BB"]

# Standard 6-max action order.
SIXMAX_ORDER = ["UTG", "HJ", "CO", "BTN", "SB", "BB"]

# 6-max -> 8-max chart mapping.
# Rationale: in 6-max each non-blind seat is one "step closer" to the button
# than the analogous 8-max position. The closest looseness match is:
#   6-max UTG (4 off the button) ~= 8-max LJ (4 off the button)
#   6-max HJ  (3 off the button) ~= 8-max HJ
#   6-max CO  (2 off the button) ~= 8-max CO
#   6-max BTN (1 off the button) ~= 8-max BTN
#   6-max SB                    -> SB
#   6-max BB                    -> BB
SIXMAX_TO_CHART = {
    "UTG": "LJ",
    "HJ": "HJ",
    "CO": "CO",
    "BTN": "BTN",
    "SB": "SB",
    "BB": "BB",
}


def detect_position(game_state):
    """Best-effort position string from a game_state dict.

    Returns a position name from SIXMAX_ORDER if the table is 6-handed, or
    from EIGHTMAX_ORDER if it's 8-handed. Falls back to None if we can't
    figure it out.

    Position is determined by SEAT (not by who's still in the hand), since
    positions are fixed at the start of the hand.
    """
    players = game_state.get("players")
    if not players:
        return None

    # First check if the player's seat is labeled directly. Engines often
    # expose a 'position' field on each player — use that if present.
    for p in players:
        if isinstance(p, dict) and (p.get("is_me") or p.get("is_self") or p.get("hero")):
            label = p.get("position")
            if label and isinstance(label, str) and label.upper() in (
                "UTG", "UTG1", "UTG2", "LJ", "HJ", "MP", "CO", "BTN", "SB", "BB"
            ):
                # Normalize MP to HJ for 6-max.
                lbl = label.upper()
                return "HJ" if lbl == "MP" else lbl

    n = len(players)  # Use full table size, not just active players.

    btn_idx = _find_button_index(players)
    me_idx = _find_my_index(players)
    if btn_idx is None or me_idx is None:
        return None

    # Pre-flop action order: SB, BB post first, then UTG acts first. Seat
    # indices in *action order* (UTG first ... BB last):
    #   action_order[0] = (btn + 3) % n  (UTG)
    #   ...
    #   action_order[n-3] = (btn) % n    (BTN)
    #   action_order[n-2] = (btn + 1) % n (SB)
    #   action_order[n-1] = (btn + 2) % n (BB)
    if n == 2:
        # Heads-up: SB is on the button.
        if me_idx == btn_idx:
            return "SB"
        return "BB"

    action_order = []
    for i in range(n - 2):
        action_order.append((btn_idx + 3 + i) % n)
    action_order.append((btn_idx + 1) % n)  # SB
    action_order.append((btn_idx + 2) % n)  # BB

    if n == 6:
        labels = SIXMAX_ORDER
    elif n == 8:
        labels = EIGHTMAX_ORDER
    else:
        labels = _generic_labels(n)

    for ord_idx, seat in enumerate(action_order):
        if seat == me_idx:
            return labels[ord_idx] if ord_idx < len(labels) else None
    return None


def chart_position(game_state):
    """Map detected seat label to a chart key in `RANGES_BY_POSITION`.

    Use this when querying ranges from `gto.ranges`.
    """
    pos = detect_position(game_state)
    if pos is None:
        return None
    players = game_state.get("players") or []
    if len(players) <= 6:
        return SIXMAX_TO_CHART.get(pos, pos)
    return pos


def is_unopened(game_state):
    """True if no player has raised yet pre-flop (we're facing only blinds)."""
    if game_state.get("street", "preflop") != "preflop":
        return False
    log = game_state.get("action_log", [])
    for entry in log:
        action = (entry.get("action") or "").lower() if isinstance(entry, dict) else str(entry).lower()
        # Anything except blind posts / folds / checks would indicate a raise.
        # Be conservative — bet/raise/all_in count as "opened."
        if any(tok in action for tok in ("raise", "bet", "all_in", "allin")):
            return False
    return True


# ---------------------------------------------------------------------------
# Internal helpers — these guess at the engine schema. Adapt if needed.
# ---------------------------------------------------------------------------
def _is_active(player):
    if isinstance(player, dict):
        if player.get("folded"):
            return False
        if player.get("status") == "folded":
            return False
        if player.get("in_hand") is False:
            return False
    return True


def _find_button_index(players):
    for i, p in enumerate(players):
        if not isinstance(p, dict):
            continue
        if p.get("is_button") or p.get("dealer") or p.get("position") == "BTN":
            return i
    return None


def _find_my_index(players):
    for i, p in enumerate(players):
        if not isinstance(p, dict):
            continue
        if p.get("is_me") or p.get("is_self") or p.get("hero"):
            return i
    return None


def _generic_labels(n):
    """Build a positional label list for non-standard table sizes."""
    # Always end with SB, BB. Fill UTG/HJ/CO/BTN-equivalents before them.
    base = ["UTG"] + [f"UTG{i}" for i in range(1, n - 5)] + ["LJ", "HJ", "CO", "BTN"]
    base = base[-(n - 2):]  # trim
    return base + ["SB", "BB"]

# ============================================================
# gto/postflop.py
# ============================================================

# Tunables — these are the dials you'll want to twist after sparring.
CBET_FREQ_HU_DRY = 0.85       # heads-up c-bet on dry boards as PFR
CBET_FREQ_HU_WET = 0.55       # heads-up c-bet on wet boards as PFR
CBET_FREQ_MULTIWAY = 0.30     # multiway c-bet (much tighter)
VALUE_BET_EQUITY_THRESHOLD = 0.60
RAISE_FOR_VALUE_EQUITY_THRESHOLD = 0.72
BLUFF_RAISE_EQUITY_THRESHOLD = 0.30  # need decent equity to bluff-raise
DRAW_CALL_MAX_POT_FRAC = 0.45        # don't call huge bets with naked draws
MIN_BLUFF_EQUITY = 0.18

# Pre-river equity adjustment vs random — opponents who called/raised
# preflop are stronger than random, so we down-shade equity.
EQ_SHADE_VS_CALLER = 0.92
EQ_SHADE_VS_RAISER = 0.85


def decide_postflop(state, rng, n_iters=1500):
    """Return an action dict for a postflop spot.

    Plays the hand to value or pot odds, with bet sizing tied to board
    wetness and hand strength.
    """
    hole = state.get("your_cards", [])
    board = state.get("community_cards", [])
    pot = max(1, state.get("pot", 1))
    owed = state.get("amount_owed", 0)
    can_check = state.get("can_check", owed == 0)
    stack = state.get("your_stack", 0)
    current_bet = state.get("current_bet", 0)

    n_opp = _count_active_opponents(state)
    if n_opp <= 0:
        return _check_or_fold(state)

    texture = analyze_board(board)
    is_pfr = _are_we_the_preflop_raiser(state)
    facing_bet = owed > 0

    # Equity is vs random; we shade based on whether we faced action.
    eq_raw = equity_vs_random(hole, board, n_opponents=n_opp, n_iters=n_iters)
    shade = _equity_shade(state, facing_bet)
    eq = eq_raw * shade

    cls = hand_strength_class(eq)

    # Pot odds when facing a bet
    pot_odds = owed / (pot + owed) if facing_bet else 0.0

    # ---------------- Facing a bet ----------------
    if facing_bet:
        return _facing_bet_decision(
            state, eq, cls, pot_odds, texture, n_opp, rng,
        )

    # ---------------- Checked to / we lead -----------
    return _no_bet_decision(
        state, eq, cls, texture, n_opp, is_pfr, rng,
    )


# ---------------------------------------------------------------------------
# Decision branches
# ---------------------------------------------------------------------------
def _facing_bet_decision(state, eq, cls, pot_odds, texture, n_opp, rng):
    """We owe chips. Raise / call / fold."""
    pot = max(1, state.get("pot", 1))
    owed = state.get("amount_owed", 0)
    facing_size_pct = owed / pot if pot > 0 else 1.0

    # Raise-for-value
    if eq >= RAISE_FOR_VALUE_EQUITY_THRESHOLD and n_opp == 1:
        target = _raise_size(state, texture, fraction=1.0)  # ~pot-sized raise
        return _legal_raise(state, target)

    # Mid-strong hand: call most bets, raise occasionally for protection
    if cls == "strong":
        # Mix raise on dry boards (deny equity), call on wet (let them barrel)
        if texture["wetness"] < 0.35 and n_opp == 1 and rng.random() < 0.35:
            target = _raise_size(state, texture, fraction=0.75)
            return _legal_raise(state, target)
        return {"action": "call"}

    # Medium / weak made: pure call/fold based on pot odds
    if cls in ("medium", "weak_made"):
        if eq > pot_odds + 0.05:
            return {"action": "call"}
        return {"action": "fold"}

    # Draw: call if pot odds + implied odds reasonable
    if cls == "draw":
        if facing_size_pct < DRAW_CALL_MAX_POT_FRAC and eq > pot_odds:
            return {"action": "call"}
        # Semi-bluff raise small portion of the time on wet boards
        if texture["wetness"] > 0.5 and rng.random() < 0.15:
            target = _raise_size(state, texture, fraction=1.0)
            return _legal_raise(state, target)
        return {"action": "fold"}

    # Air — fold to almost everything; occasionally raise as a pure bluff
    # but only with blockers and small facing size
    if cls == "air":
        if facing_size_pct < 0.5 and rng.random() < 0.04:
            target = _raise_size(state, texture, fraction=1.0)
            return _legal_raise(state, target)
        return {"action": "fold"}

    return {"action": "fold"}


def _no_bet_decision(state, eq, cls, texture, n_opp, is_pfr, rng):
    """It's checked to us. Bet or check."""
    pot = max(1, state.get("pot", 1))

    # Monster / strong: bet for value
    if cls == "monster":
        # Slow-play occasionally on dry boards to induce action
        if texture["wetness"] < 0.25 and rng.random() < 0.20:
            return {"action": "check"}
        size = _value_bet_size(state, texture, big=True)
        return _legal_raise(state, size)

    if cls == "strong":
        size = _value_bet_size(state, texture, big=False)
        return _legal_raise(state, size)

    # Medium-strength hand: thin value HU, check multiway
    if cls == "medium":
        if n_opp == 1 and eq > VALUE_BET_EQUITY_THRESHOLD:
            size = _value_bet_size(state, texture, big=False, thin=True)
            return _legal_raise(state, size)
        return {"action": "check"}

    # Weak made hand with showdown value — check
    if cls == "weak_made":
        return {"action": "check"}

    # Draw — semi-bluff some fraction of the time
    if cls == "draw":
        if n_opp == 1 and rng.random() < (0.55 if texture["wetness"] > 0.4 else 0.35):
            size = _semibluff_size(state, texture)
            return _legal_raise(state, size)
        return {"action": "check"}

    # Air — c-bet as PFR sometimes, otherwise check
    if cls == "air":
        if is_pfr:
            cbet_freq = (CBET_FREQ_MULTIWAY if n_opp >= 2 else
                         (CBET_FREQ_HU_WET if texture["wetness"] > 0.4
                          else CBET_FREQ_HU_DRY))
            # Don't c-bet pure trash; need a tiny bit of equity
            if eq >= MIN_BLUFF_EQUITY and rng.random() < cbet_freq:
                size = _cbet_size(state, texture)
                return _legal_raise(state, size)
        return {"action": "check"}

    return {"action": "check"}


# ---------------------------------------------------------------------------
# Sizing
# ---------------------------------------------------------------------------
def _value_bet_size(state, texture, big=False, thin=False):
    pot = max(1, state.get("pot", 1))
    current_bet = state.get("current_bet", 0)
    street = state.get("street", "preflop")

    if street == "river":
        frac = 0.85 if big else (0.60 if not thin else 0.45)
    else:
        # Flop/turn: bigger on wet boards to charge draws
        base = 0.75 if big else 0.55
        if texture["wetness"] > 0.5:
            base += 0.15
        if thin:
            base = min(base, 0.45)
        frac = base

    return current_bet + int(frac * pot)


def _cbet_size(state, texture):
    pot = max(1, state.get("pot", 1))
    current_bet = state.get("current_bet", 0)
    # Small c-bet on dry boards, larger on wet
    if texture["wetness"] < 0.25:
        frac = 0.33
    elif texture["wetness"] < 0.5:
        frac = 0.5
    else:
        frac = 0.66
    return current_bet + int(frac * pot)


def _semibluff_size(state, texture):
    pot = max(1, state.get("pot", 1))
    current_bet = state.get("current_bet", 0)
    frac = 0.6 if texture["wetness"] > 0.4 else 0.5
    return current_bet + int(frac * pot)


def _raise_size(state, texture, fraction=1.0):
    """Size a raise to ~fraction * pot ON TOP of the current bet."""
    pot = max(1, state.get("pot", 1))
    current_bet = state.get("current_bet", 0)
    return current_bet + int(fraction * pot)


# ---------------------------------------------------------------------------
# State inspection
# ---------------------------------------------------------------------------
def _count_active_opponents(state):
    players = state.get("players") or []
    n = 0
    for p in players:
        if not isinstance(p, dict):
            continue
        if p.get("is_me") or p.get("is_self") or p.get("hero"):
            continue
        if p.get("folded") or p.get("status") == "folded":
            continue
        n += 1
    # Fallback if no metadata: assume 1 opponent.
    return n if n > 0 else 1


def _are_we_the_preflop_raiser(state):
    """Scan preflop action log for last raise, see if it was us."""
    log = state.get("action_log", [])
    last_raiser = None
    for entry in log:
        if not isinstance(entry, dict):
            continue
        street = entry.get("street", "preflop")
        if street != "preflop":
            continue
        action = (entry.get("action") or "").lower()
        if "raise" in action or "bet" in action or "all_in" in action or "allin" in action:
            last_raiser = entry.get("player") or entry.get("seat")
    if last_raiser is None:
        return False
    # Engine-dependent: "me", "hero", or our seat index.
    if isinstance(last_raiser, str):
        return last_raiser.lower() in ("me", "hero", "self")
    if isinstance(last_raiser, int):
        players = state.get("players") or []
        if 0 <= last_raiser < len(players):
            p = players[last_raiser]
            return isinstance(p, dict) and (p.get("is_me") or p.get("is_self") or p.get("hero"))
    return False


def _equity_shade(state, facing_bet):
    """Down-shade equity-vs-random when there's been preflop action.

    Players who paid to see the flop are tighter than random — our
    hand-vs-random number overstates our equity.
    """
    log = state.get("action_log", [])
    raises = 0
    for entry in log:
        if not isinstance(entry, dict):
            continue
        if entry.get("street", "preflop") != "preflop":
            continue
        action = (entry.get("action") or "").lower()
        if "raise" in action or "bet" in action:
            raises += 1
    if raises >= 2:
        return EQ_SHADE_VS_RAISER  # 3-bet pot or similar
    if raises >= 1:
        return EQ_SHADE_VS_CALLER
    return 1.0


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------
def _check_or_fold(state):
    if state.get("can_check"):
        return {"action": "check"}
    return {"action": "fold"}


def _legal_raise(state, target):
    """Snap target to legal bounds. Falls back to all_in if we'd commit."""
    target = max(target, state.get("min_raise_to", target))
    stack = state.get("your_stack", 0)
    current_bet = state.get("current_bet", 0)
    if target >= current_bet + stack:
        return {"action": "all_in"}
    return {"action": "raise", "amount": int(target)}

# ============================================================
# gto/strategy.py
# ============================================================

import random



# Stack-depth threshold below which we switch to jam-or-fold mode.
SHORT_STACK_BB = 20.0


def decide(game_state, rng=None, equity_iters=1500):
    """Main entry point. Returns one of:
        {"action": "fold"}
        {"action": "check"}
        {"action": "call"}
        {"action": "raise", "amount": <int>}
        {"action": "all_in"}
    """
    rng = rng or random
    try:
        street = game_state.get("street", "preflop")
        if street == "preflop":
            return _preflop(game_state, rng)
        return decide_postflop(game_state, rng, n_iters=equity_iters)
    except Exception:
        # Hard safety net: never crash the bot.
        if game_state.get("can_check"):
            return {"action": "check"}
        return {"action": "fold"}


# ---------------------------------------------------------------------------
# Pre-flop routing
# ---------------------------------------------------------------------------
def _preflop(state, rng):
    hand = canonical(state["your_cards"])
    pos = chart_position(state)
    eff_bb = effective_stack_bb(state)

    # Detect what kind of preflop spot we're in.
    history = _preflop_history(state)
    facing_jam = _is_facing_jam(state)
    n_preflop_raises = history["raises"]

    # --- Short-stack push/fold mode ---
    if eff_bb <= SHORT_STACK_BB:
        return _short_stack(state, hand, pos, history, facing_jam, eff_bb, rng)

    # --- 100bb chart mode ---
    if facing_jam:
        # Someone shoved on us — call range
        return _call_jam_decision(state, hand, history)

    if is_unopened(state) and n_preflop_raises == 0:
        return _open_decision(state, hand, pos, rng)

    if n_preflop_raises == 1 and history["last_raiser_was_us"]:
        # We opened and are now facing a 3-bet
        return _vs_3bet(state, hand, rng)

    if n_preflop_raises >= 1:
        # Someone opened (or 3-bet) before us
        return _defense_decision(state, hand, pos, history, rng)

    # Fall-through (shouldn't reach here)
    return _check_or_fold(state)


def _open_decision(state, hand, pos, rng):
    """First in. Use the RFI chart."""
    if pos is None:
        return _check_or_fold(state)

    # Heads-up override: the 8-max SB chart is heavily limp-based because
    # it assumes 6 opponents already folded. In HU there are no other
    # folders to worry about — SB is the button. Standard HU button opens
    # ~75–85% of hands.
    n_active = _count_seats_in_hand(state)
    if n_active == 2 and pos == "SB":
        return _hu_btn_open(state, hand, rng)

    dist = get_open_action(pos, hand)
    chosen = _sample(dist, rng)

    if chosen == "fold":
        return _check_or_fold(state)
    if chosen == "call":
        return {"action": "call"}
    if chosen == "raise":
        size_bb = OPEN_SIZE_BB.get(pos, 2.5)
        amount = _bb_to_chips(state, size_bb)
        return _legal_raise(state, amount)
    return _check_or_fold(state)


# Heads-up button (=SB) open range. Excludes only the absolute worst trash.
_HU_BTN_NEVER_OPEN = {
    "72o", "73o", "62o", "63o", "52o", "53o", "42o", "43o", "32o",
    "82o", "83o", "92o", "93o",
}


def _hu_btn_open(state, hand, rng):
    """HU button open — raise wide, fold only the worst trash."""
    if hand in _HU_BTN_NEVER_OPEN:
        # Even these fold less than 100% in true GTO, but they're close.
        if rng.random() < 0.1:
            size = _bb_to_chips(state, 2.5)
            return _legal_raise(state, size)
        return _check_or_fold(state)
    size = _bb_to_chips(state, 2.5)
    return _legal_raise(state, size)


def _count_seats_in_hand(state):
    """How many seats are still active (not folded)?"""
    players = state.get("players") or []
    n = 0
    for p in players:
        if not isinstance(p, dict):
            n += 1
            continue
        if p.get("folded") or p.get("status") == "folded":
            continue
        n += 1
    return n if n > 0 else len(players)


def _defense_decision(state, hand, our_pos, history, rng):
    """Facing a raise (or raise + caller). Use defense ranges."""
    opener_pos = history["first_raiser_pos"] or "HJ"
    dist = defense_action(opener_pos, our_pos or "BB", hand)
    chosen = _sample(dist, rng)

    if chosen == "fold":
        return _check_or_fold(state)
    if chosen == "call":
        return {"action": "call"}
    if chosen == "3bet":
        # Size: ~3x opener IP, ~4x OOP (rough heuristic)
        opener_size = _last_raise_to(state)
        in_position = _will_be_in_position(opener_pos, our_pos)
        multiplier = 3.0 if in_position else 4.0
        target = int(opener_size * multiplier)
        return _legal_raise(state, target)
    return _check_or_fold(state)


def _vs_3bet(state, hand, rng):
    """We opened and someone 3-bet. Use 4-bet defense range."""
    dist = four_bet_defense(hand)
    chosen = _sample(dist, rng)

    if chosen == "fold":
        return {"action": "fold"}
    if chosen == "call":
        return {"action": "call"}
    if chosen == "3bet":
        # "3bet" in this table actually means 4-bet (we're the one
        # raising again). Size ~2.25x their 3-bet.
        three_bet_to = _last_raise_to(state)
        target = int(three_bet_to * 2.25)
        return _legal_raise(state, target)
    return {"action": "fold"}


# ---------------------------------------------------------------------------
# Short-stack mode
# ---------------------------------------------------------------------------
def _short_stack(state, hand, pos, history, facing_jam, eff_bb, rng):
    if facing_jam:
        return _call_jam_decision(state, hand, history)

    # If unopened, consider open-jamming.
    if history["raises"] == 0:
        jam_pos = pos or "BTN"
        if hand in open_jam_hands(eff_bb, jam_pos):
            return {"action": "all_in"}
        # Below 12bb we should be jamming-or-folding entirely
        if eff_bb <= 12:
            return _check_or_fold(state)
        # 12–20bb: with strong-but-not-jam hands, mini-raise
        dist = get_open_action(pos or "BTN", hand)
        if dist.get("raise", 0) > 0.5:
            size = _bb_to_chips(state, 2.2)
            return _legal_raise(state, size)
        return _check_or_fold(state)

    # Facing a raise but not a jam: tighter version of the standard defense
    return _defense_decision(state, hand, pos, history, rng)


def _call_jam_decision(state, hand, history):
    """Someone went all-in. Decide call vs fold using call ranges."""
    jammer_pos = history["last_raiser_pos"] or history["first_raiser_pos"] or "BTN"
    call_range = call_jam_range(jammer_pos)
    if hand in call_range:
        return {"action": "call"}
    return {"action": "fold"}


# ---------------------------------------------------------------------------
# History parsing
# ---------------------------------------------------------------------------
def _preflop_history(state):
    """Inspect action_log for preflop actions.

    Returns a dict:
        raises: count of raises this street
        first_raiser_pos: position name of the first raiser (or None)
        last_raiser_pos:  position name of the most recent raiser (or None)
        last_raiser_was_us: True iff the most recent raiser is us
    """
    info = {
        "raises": 0,
        "first_raiser_pos": None,
        "last_raiser_pos": None,
        "last_raiser_was_us": False,
    }
    log = state.get("action_log", [])
    players = state.get("players") or []

    for entry in log:
        if not isinstance(entry, dict):
            continue
        if entry.get("street", "preflop") != "preflop":
            continue
        action = (entry.get("action") or "").lower()
        if "raise" in action or "all_in" in action or "allin" in action or "bet" in action:
            info["raises"] += 1
            player_ref = entry.get("player") or entry.get("seat")
            pos = _resolve_position(player_ref, players)
            if info["first_raiser_pos"] is None:
                info["first_raiser_pos"] = pos
            info["last_raiser_pos"] = pos
            info["last_raiser_was_us"] = _player_is_us(player_ref, players)
    return info


def _resolve_position(player_ref, players):
    """Best-effort: turn a player ref into a position string."""
    if isinstance(player_ref, dict):
        return player_ref.get("position")
    if isinstance(player_ref, str):
        # Engine might pass "UTG" directly, or a seat name.
        if player_ref.upper() in ("UTG", "UTG1", "LJ", "HJ", "MP", "CO", "BTN", "SB", "BB"):
            return "HJ" if player_ref.upper() == "MP" else player_ref.upper()
    if isinstance(player_ref, int) and 0 <= player_ref < len(players):
        p = players[player_ref]
        if isinstance(p, dict):
            return p.get("position")
    return None


def _player_is_us(player_ref, players):
    if isinstance(player_ref, str):
        return player_ref.lower() in ("me", "hero", "self")
    if isinstance(player_ref, int) and 0 <= player_ref < len(players):
        p = players[player_ref]
        return isinstance(p, dict) and (p.get("is_me") or p.get("is_self") or p.get("hero"))
    return False


def _is_facing_jam(state):
    """True if the bet we're facing is an all-in."""
    owed = state.get("amount_owed", 0)
    stack = state.get("your_stack", 0)
    # If calling would put us all-in, treat it as a jam decision
    if stack > 0 and owed >= stack:
        return True
    # Also check log for an explicit all_in action this street
    log = state.get("action_log", [])
    for entry in log[-6:]:  # only recent
        if isinstance(entry, dict):
            action = (entry.get("action") or "").lower()
            if "all_in" in action or "allin" in action:
                return True
    return False


def _last_raise_to(state):
    """The current bet amount (which is also the most recent raise target)."""
    return state.get("current_bet", 0) or state.get("min_raise_to", 0) or 1


def _will_be_in_position(opener_pos, our_pos):
    """True if our_pos acts after opener_pos post-flop."""
    order = ["UTG", "UTG1", "LJ", "HJ", "CO", "BTN", "SB", "BB"]
    try:
        # SB and BB act first post-flop (worst position)
        if our_pos in ("SB", "BB"):
            return False
        if opener_pos in ("SB", "BB"):
            return True
        return order.index(our_pos) > order.index(opener_pos)
    except ValueError:
        return False


# ---------------------------------------------------------------------------
# Sampling / sizing primitives
# ---------------------------------------------------------------------------
def _sample(dist, rng):
    """Sample from {name: freq} distribution."""
    r = rng.random()
    cum = 0.0
    for name, freq in dist.items():
        cum += freq
        if r < cum:
            return name
    return max(dist.items(), key=lambda kv: kv[1])[0]


def _bb_to_chips(state, size_bb):
    bb_size = state.get("big_blind") or state.get("current_bet") or 100
    return int(size_bb * bb_size)


def _legal_raise(state, target):
    target = max(int(target), state.get("min_raise_to", target))
    stack = state.get("your_stack", 0)
    current_bet = state.get("current_bet", 0)
    if target >= current_bet + stack:
        return {"action": "all_in"}
    return {"action": "raise", "amount": int(target)}


def _check_or_fold(state):
    return {"action": "check"} if state.get("can_check") else {"action": "fold"}

# ============================================================
# Entry point
# ============================================================
# `decide(game_state)` is defined in the strategy section above.
