"""Bundle the gto/ package into a single bot.py for tournament submission.

Run:
    python3 build_single_file.py

Output:
    dist/bot.py  — drop this directly into your submission zip (or upload alone).
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).parent
SRC_FILES = [
    "gto/hand_notation.py",
    "gto/equity.py",
    "gto/board.py",
    "gto/ranges.py",
    "gto/defense.py",
    "gto/pushfold.py",
    "gto/position.py",
    "gto/postflop.py",
    "gto/strategy.py",
]

HEADER = '''"""
Single-file GTO bot — generated by build_single_file.py.
Do not edit directly. Edit the gto/ package and rebuild.

This file is the concatenation of:
    gto/hand_notation.py
    gto/ranges.py
    gto/position.py
    gto/strategy.py

Submission entry point is `decide(game_state)` at the bottom.
"""

'''


def strip_internal_imports(text):
    """Remove `from .module import X` lines — everything is in this file now."""
    return re.sub(r"^from \.\S+ import .*$\n", "", text, flags=re.MULTILINE)


def strip_module_docstring(text):
    """Drop the leading triple-quoted module docstring (we have our own)."""
    return re.sub(r'^"""[\s\S]*?"""\n', "", text, count=1)


def main():
    out_dir = ROOT / "dist"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "bot.py"

    parts = [HEADER]
    for src in SRC_FILES:
        body = (ROOT / src).read_text()
        body = strip_module_docstring(body)
        body = strip_internal_imports(body)
        parts.append(f"# ============================================================\n")
        parts.append(f"# {src}\n")
        parts.append(f"# ============================================================\n\n")
        parts.append(body.strip())
        parts.append("\n\n")

    # Export `decide` at module level — already defined in strategy.py.
    parts.append(
        "# ============================================================\n"
        "# Entry point\n"
        "# ============================================================\n"
        "# `decide(game_state)` is defined in the strategy section above.\n"
    )

    out_path.write_text("".join(parts))
    print(f"Wrote {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
